config/routes.rb
Rails.application.routes.draw do
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
	mount_uploader :csv, CsvUploader
	has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include StructureHelper, CsvHelper
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page_structure = Page.find_by(parent_path: '', csv_id: @page.csv_id).subtree.arrange
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    validate_csv(@page)
    respond_to do |format|
      if @page.errors.blank?
        @master_page = process_csv(@page.csv)
        format.html { redirect_to @master_page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: master_page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:csv)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_helper.rb
require 'csv'

module CsvHelper
	def validate_csv(page)
		return page if !page.valid?
		csv_content = page.csv.read
		begin
			CSV.parse(csv_content, headers: true)
		rescue CSV::MalformedCSVError => exception
			page.errors.add(:base, exception.inspect)
		end
	end

	def process_csv(csv)
		csv_content = csv.read
		pages = CSV.parse(csv_content, headers: true)
		master_page = ''
		pages.each do |page|
			if page["parent_path"].nil?
				page["parent_path"] = ''
				master_page = page			
			end
			relative_path = page["parent_path"] + page["slug"]
			new_page = Page.create(name: page["name"], 
														 parent_path: page["parent_path"], 
														 slug: page["slug"],
														 csv_id: csv.url,
														 relative_path: relative_path)
			new_page.save!
			assign_parent(new_page) unless new_page.parent_path.blank?
			master_page = new_page.root
		end

		master_page
	end

	def assign_parent(page)
		if page.parent_path != '/'
			parent_page_slug = page.parent_path.gsub('/', '')
		else
			parent_page_slug = page.parent_path
		end
		parent_page = Page.find_by(slug: parent_page_slug, csv_id: page.csv_id)
		page.parent = parent_page
		page.save!
	end
end  

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/structure_helper.rb
module StructureHelper
	def arranged_tree_as_list(hash, options = {}, &block)

    options = {
      :list_type            => :ul,
      :list_style           => '', 
      :ul_class             => [],
      :ul_class_top         => [],
      :ul_class_children    => ['nested'],
      :li_class             => [],
      :li_class_top         => [],
      :li_class_children    => [],
      :sort_by              => []
    }.merge(options)

    # setup any custom list styles you want to use here. An example is excluded
    # to render bootstrap style list groups. This is used to keep from recoding the same
    # options on different lists
    case options[:list_style]
      when :bootstrap_list_group
        options[:ul_class] << ['list-group']
        options[:li_class] << ['list-group-item']
    end
    options[:list_style] = ''

    output = ''

    # sort the hash key based on sort_by options array
    unless options[:sort_by].empty?
      hash = Hash[hash.sort_by{|k, v| options[:sort_by].collect {|sort| k.send(sort)} } ]
    end

    current_depth = 0
    # and here... we... go...
    hash.each do |object, children|

        li_classes = options[:li_class]  
              
        if object.depth == 0
          li_classes += options[:li_class_top]
        else
          li_classes += options[:li_class_children]
        end 
               
        if children.size > 0
        	#byebug
          output << content_tag(:li, capture(object, &block) + arranged_tree_as_list(children, options, &block).html_safe,  :class => li_classes)
        else
          output << content_tag(:li, capture(object, &block), :class => li_classes).html_safe
          current_depth = object.depth
        end

    end

    unless output.blank?
      
      ul_classes = options[:ul_class]
      
      if current_depth == 0
        ul_classes += options[:ul_class_top]
      else
        ul_classes += options[:ul_class_children]
      end      
      #byebug
      output = content_tag(options[:list_type], output.html_safe, :class => ul_classes)
    end
    
    return output.html_safe
  end  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PageStructure</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :csv %>
    <%= form.file_field :csv, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/_tree_node.html.erb
<div style="margin-left:20px">
	<p>
	  <strong>PATH:</strong>
	  PPP === <%= page.name %>
	</p>
</div>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>
<h2><%= link_to 'Create New Page', new_page_path %></h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Relative Path</th>
      <th>Parent Path</th>
      <th>Slug</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.name %></td>
        <td><%= page.relative_path %></td>
        <td><%= page.parent_path %></td>
        <td><%= page.slug %></td>
        <% if page.parent.blank? %>
          <td><%= link_to 'Show Page Structure', page %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'View Saved Page Structures', pages_path %>

app/views/pages/show.html.erb
<style>
/* Remove default bullets */
ul, #myUL {
  list-style-type: none;
}

/* Remove margins and padding from the parent ul */
#myUL {
  margin: 0;
  padding: 0;
}

/* Style the caret/arrow */
.caret {
  cursor: pointer; 
  user-select: none;
  border-left: 8px solid transparent;
  border-right: 8px solid transparent;
  border-top: 8px solid #000000;
}

/* Create the caret/arrow with a unicode, and style it */

/* Rotate the caret/arrow icon when clicked on (using JavaScript) */
.caret-down::before {
  transform: rotate(90deg); 
}

/* Hide the nested list */
.nested {
  display: none;
}

/* Show the nested list when the user clicks on the caret/arrow (with JavaScript) */
.active {
  display: block;
}
</style>
<p id="notice"><%= notice %></p>
<p>
  <strong>CSV FILE:</strong>
  <%= @page.csv_id %>
</p>

<p>
	<strong>PAGE STRUCTURE:</strong>
	<p>Click Caret to View Child Pages</p>
	<%= arranged_tree_as_list(@page_structure) do |page| %>
		<% if page.children.present? %>
	  	<span class="caret"></span><%= page.name %> - '<%= page.relative_path %>'
	  <% else %>
	  	<%= page.name %> - '<%= page.relative_path %>'
	  <% end %>
	<% end %>
</p>
<%= link_to 'View Saved Page Structures', pages_path %>
<br>
<%= link_to 'Create New Page', new_page_path %>
<script>
var toggler = document.getElementsByClassName("caret");
var i;

for (i = 0; i < toggler.length; i++) {
  toggler[i].addEventListener("click", function() {
    this.parentElement.querySelector(".nested").classList.toggle("active");
    this.classList.toggle("caret-down");
  });
}
</script>